---
- name: Compile Java on master
  hosts: master                   # Target the master host
  remote_user: ubuntu             # Replace with your actual user if different
  become: yes                     # Use sudo to execute tasks with elevated privileges
  tasks:
    - name: Run comp.sh
      shell: |
       sudo -u ubuntu /usr/bin/bash -ilc '/home/ubuntu/comp.sh'
      args:
        chdir: /home/ubuntu/
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
